version: "3.8"

services:
  shop-ddd:
    build: .
    container_name: shop-ddd
    ports:
      - "${APP_PORT}:3000"
    environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    depends_on:
      - db
  migrate:
    image: migrate/migrate
    restart: on-failure
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    command: [
        "-path", "/migrations",
        "-database", "postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?sslmode=disable",
        "up"
    ]
  db:
    image: postgres:15
    container_name: shop-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
